---
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build Docker images

    steps:
    - uses: actions/checkout@v2

    - name: Set short commit hash
      run: echo "SHORT_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Docker build
      run: docker build . -t bla:latest

  use:
    runs-on: ubuntu-latest
    name: "Try artifact"
    needs: build
    
    steps:
    - uses: actions/checkout@v2

    - name: Run it
      run: docker run --rm bla:latest ls