---
name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build Docker images

    steps:
    - uses: actions/checkout@v2

    - name: Set short commit hash
      run: echo "SHORT_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Docker build
      run: docker build . -t bla:${{ env.SHORT_TAG }}


  use:
    runs-on: ubuntu-latest

    name: "Hello?"
    run: docker run  --rm -it -e IMAGE=bla:${{ env.SHORT_TAG }}