---
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build Docker images

    steps:
    - uses: actions/checkout@v2

    - name: Set short commit hash
      run: echo "SHORT_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Docker build
      run: docker build . -t prod_image:latest


    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "prod_image:latest"

  use:
    runs-on: ubuntu-latest
    name: "Try artifact"
    needs: build
    
    steps:
    - uses: actions/checkout@v2


    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "prod_image:latest"

    - name: Run it
      run: docker run --rm prod_image:latest ls